import { chmodSync, copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { p, pc } from "@fleet/core";
import { initBus, swarmPaths, type ThreadSeed } from "@fleet/bus";
import { assetsDir, BOARD_FILES } from "./assets.js";
import {
  layoutFor,
  loadConfig,
  pickThreads,
  requireRoot,
  resolved,
  swarmDir,
  threadText,
  THREAD_FILE,
  type ResolvedConfig,
  type SwarmThread,
} from "./config.js";
import { startServerDetached } from "./server.js";
import { createWorktree, hideFromGit, seedMcp, writeThreadFile } from "./worktree.js";

const PALETTE = ["#7c3aed", "#0ea5e9", "#10b981", "#f59e0b", "#ef4444", "#ec4899", "#14b8a6"];

function colorFor(t: SwarmThread, i: number): string {
  return t.color ?? PALETTE[i % PALETTE.length] ?? "#7c3aed";
}

function copyBoardAssets(sd: string): void {
  const src = assetsDir();
  for (const f of BOARD_FILES) {
    const from = join(src, f);
    if (existsSync(from)) copyFileSync(from, join(sd, f));
  }
}

function writeBoardConfig(sd: string, r: ResolvedConfig, seeds: ThreadSeed[]): void {
  const threads = seeds.map((s) => ({
    name: s.name,
    title: s.title,
    color: (s as ThreadSeed & { color?: string }).color,
    branch: s.branch,
    worktree: s.worktree,
    repo: s.repo,
  }));
  writeFileSync(join(sd, "config.json"), JSON.stringify({ port: r.port, threads }, null, 2));
}

function writeLaunchScript(sd: string): void {
  const path = join(sd, "launch.sh");
  writeFileSync(
    path,
    [
      "#!/usr/bin/env bash",
      "# Generated by `fleet swarm prepare`.",
      "# YOU run this to spawn the agent surfaces (the orchestrator agent must not).",
      'exec fleet swarm launch "$@"',
      "",
    ].join("\n"),
  );
  chmodSync(path, 0o755);
}

export interface PrepareResult {
  root: string;
  r: ResolvedConfig;
  threads: SwarmThread[];
  sd: string;
}

/**
 * AGENT-SAFE preparation: create worktrees, materialize `.swarm/`, seed `.mcp.json`,
 * init the bus, and start the board server — WITHOUT spawning any agent surfaces.
 * The user runs `fleet swarm launch` afterward (the permission boundary).
 */
export function prepare(names: string[], opts: { quiet?: boolean } = {}): PrepareResult {
  const root = requireRoot();
  const cfg = loadConfig(root);
  const r = resolved(root, cfg);
  const threads = pickThreads(cfg, names);
  const sd = swarmDir(root);

  if (!existsSync(r.worktreeDir)) mkdirSync(r.worktreeDir, { recursive: true });
  mkdirSync(sd, { recursive: true });
  if (!opts.quiet) p.intro(pc.cyan(`🐝 swarm prepare — ${threads.length} thread(s), base=${r.base}`));

  const seeds: ThreadSeed[] = [];
  threads.forEach((t, i) => {
    const { branch, wtPath, startCwd } = layoutFor(r, t);
    const base = t.base ?? r.base;

    const wt = createWorktree(root, branch, wtPath, base);
    if (!wt.ok) {
      if (!opts.quiet) p.log.error(`${t.name}: worktree add failed:\n${wt.out}`);
      return;
    }
    if (wt.existed && !opts.quiet)
      p.log.warn(`${t.name}: worktree exists — refreshing THREAD.md`);

    writeThreadFile(startCwd, threadText(root, t));
    const seeded = seedMcp(root, wtPath);
    hideFromGit(wtPath, [THREAD_FILE, ...(seeded ? [".mcp.json"] : [])]);

    seeds.push({
      name: t.name,
      title: t.title ?? t.name,
      repo: t.repo ?? root,
      branch,
      worktree: wtPath,
    });
    (seeds[seeds.length - 1] as ThreadSeed & { color?: string }).color = colorFor(t, i);
    if (!opts.quiet) p.log.success(`${t.name} → ${branch} @ ${wtPath}`);
  });

  copyBoardAssets(sd);
  writeBoardConfig(sd, r, seeds);
  initBus(swarmPaths(sd), seeds);
  writeLaunchScript(sd);
  const started = startServerDetached(sd, r.port);

  if (!opts.quiet) {
    if (started) p.log.step(`board server → http://localhost:${r.port}/board.html`);
    p.outro(
      `Prepared. ${pc.bold("You")} now run ${pc.cyan("fleet swarm launch")} (or ${pc.cyan("bash .swarm/launch.sh")}) to spawn the agents.`,
    );
  }
  return { root, r, threads, sd };
}
